### ISSUE TITLE
docker-compose 

### ISSUE THREAD

**Issue by Urgen-Dorjee** [dotnet/AspNetCore.Docs#14023]
Dockerfile, this is very compact file..
```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
WORKDIR /app
EXPOSE 5000
ENV ASPNETCORE_URLS=http://*:5000

```
docker-compose file
```
web:
    image: ${DOCKER_REGISTRY-}web
    networks:
      - frontendpool
    build: 
      context: .
      dockerfile: WebManagement/Web/Dockerfile
    depends_on:
      - customerapi       
    ports:
      - "7000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    networks:
      - backendpool
     - frontendpool
    build: 
      context: .
      dockerfile: CustomerManagement/CustomerAPI/Dockerfile
    depends_on:
      - sqlserver      
    ports:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
```
I have told dockerfile to expose port 5000 and set ENV value to ASPNETCORE_URLS=http://*:5000

when I build the compose file, why is that it always set the ENV value to ASPNETCORE_URLS=http:\\+80. No matter what port you expose it always set to port 80 therefore how and why is this configuration coming from??? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
