### ISSUE TITLE
Provide example css

### ISSUE THREAD

**Issue by Siphonophora** [dotnet/AspNetCore.Docs#17485]
I had trouble getting the user alert to show up. I eventually realized the issue was because I was using styles that didn't include `blazor-error-ui`. Actually, they came from the blazing pizza demo which I was using for testing. 

Including an example from the template would help make it clear that the user might need to add the style if it was missing. 
``` css
#blazor-error-ui {
    background: lightyellow;
    bottom: 0;
    box-shadow: 0 -1px 2px rgba(0, 0, 0, 0.2);
    display: none;
    left: 0;
    padding: 0.6rem 1.25rem 0.7rem 1.25rem;
    position: fixed;
    width: 100%;
    z-index: 1000;
}

#blazor-error-ui .dismiss {
    cursor: pointer;
    position: absolute;
    right: 0.75rem;
    top: 0.5rem;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1440e7-febc-3fbc-09d7-7f47b740fd3b
* Version Independent ID: 31071595-7c71-b6f7-3856-74f78c5c7cdf
* Content: [Handle errors in ASP.NET Core Blazor apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**
