### ISSUE TITLE
How to specify the environment (--staging, --prod , etc)

### ISSUE THREAD

**Issue by SibeeshVenu** [dotnet/AspNetCore.Docs#20784]
As per the doc, the `dotnet publish` will run the `ng build --prod` in the background. To make it work with the other environment, for example `staging`, what should I do? Is this something that is possible with the `Azure DevOps Pipeline`, as I have the build, publish tasks in the pipeline. 

```
stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    condition: ne(variables['Build.Reason'], 'PullRequest')
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration $(buildConfiguration)
    - task: DotNetCoreCLI@2
      displayName: Dotnet publish
      inputs:
        command: publish
        publishWebProjects: true
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactsStagingDirectory)/$(Build.BuildId).zip'
        zipAfterPublish: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(Build.ArtifactsStagingDirectory)/$(Build.BuildId).zip
        ArtifactName: drop
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**
