### ISSUE TITLE
Auto-add assignees to new GH issues

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#24368]
@adegeo ... Does the feature exist yet to auto-add the `Assignees` via [`.repoman.yml`](https://github.com/dotnet/AspNetCore.Docs/blob/main/.repoman.yml)?

I'm hoping for the following configuration/feature (`assignees-add`) for the existing Blazor issue rules. There are **_FOUR_** rules that would need the config ...

```
pass:
  - labels-add: ["Blazor"]
  - projects-add: [35]
  - labels-remove: [":watch: Not Triaged"]
  - assignees-add: ["guardrex"]
```

If that's not a thing, is it still planned? It's the last feature that we need *to save a lot of clicks* 🖐️🖱️🙏 .
