### ISSUE TITLE
Implement automatic assignee assignment (if available)

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#26588]
@adegeo ... For https://github.com/dotnet/AspNetCore.Docs/blob/main/.repoman.yml, was the feature set extended to automatically apply assignee(s)? We'd still ❤️ implementing it to save **_a thousand clicks a day!_** 😆 

We're hoping for something like the following `assignees-add` property (using the existing Blazor config as the example) ...

```yml
- check:
    - type: metadata-comment
      name: content source
      value: "(?i).*blazor.*"
  pass:
    - labels-add: ["Blazor"]
    - projects-add: [35]
    - labels-remove: [":watch: Not Triaged"]
    - assignees-add: ["guardrex"]
```
