### ISSUE TITLE
Test Issue (No Description)

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#33897]
### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md

### Document ID

3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc)

**Comment by guardrex** [comment]
@adegeo ... We've had some problems with labeling lately (for example, I had to add the service and sub-service labels to https://github.com/dotnet/AspNetCore.Docs/issues/33896), and I'm running some tests to see what pattern isn't adding labels correctly.

In this first test, I opened the issue without changing the description. I can see Repoman running ...

```
    # Try to detect an empty issue
    - check:
        - type: comment-body
          value: "### Description[\\n\\r]+\\[Enter feedback here\\][\\n\\r]+###"
      pass:
        - labels-add: ["needs-more-info"]
        - labels-remove: [":watch: Not Triaged"]
        - close
```

... but the `close` isn't effective. This issue was closed and then re-opened, and then the rest of the processing ran. It doesn't seem like that was your intention with the `close` command.
